# Backend Benchmark Exploration

Use this notebook first. It runs the ChromaDB vs pgvector benchmark and shows pandas DataFrames for speed, retrieval quality, scores, and ranking parity. Nothing is written to `evaluation_results.json` unless you run the optional save cell at the end.

## Before Running

- Make sure `.env` points `PDF_SOURCE_DIR` at your PDFs.
- Make sure chunks already exist under `data/interim/chunks/`; if not, run `python pipeline.py extract` first.
- For pgvector, run `docker compose up -d`, `alembic upgrade head`, and `python scripts/check_pgvector.py`.
- If imports fail, check the kernel path in the next cell. VS Code/Jupyter must use the same environment where the project dependencies are installed.

In [1]:
import sys

print(sys.executable)
print(sys.version)
# If this path is not your project environment, switch kernels in VS Code.
# To install dependencies into this exact kernel, run:
# %pip install -r requirements.txt

/opt/anaconda3/envs/project-d/bin/python
3.12.13 | packaged by Anaconda, Inc. | (main, Mar 19 2026, 20:12:32) [Clang 20.1.8 ]

In [2]:
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path.cwd()
if not (REPO_ROOT / "pipeline.py").exists():
    REPO_ROOT = REPO_ROOT.parent

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from benchmark_metrics import (
    run_backend_benchmark,
    summarise_results,
    write_results_json,
)

pd.set_option("display.max_colwidth", 140)
pd.set_option("display.precision", 6)

/opt/anaconda3/envs/project-d/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Parameters

For a quick smoke test, set `MAX_CHUNKS` or `MAX_QUERIES` to a small number. For the professor's spec, eventually use 20 representative queries and `QUERY_REPEATS = 3`.

In [3]:
BACKENDS = ("chroma", "pgvector")
BATCH_SIZE = 256
QUERY_REPEATS = 3
K = 5
MAX_CHUNKS = None
MAX_QUERIES = None

{
    "backends": BACKENDS,
    "batch_size": BATCH_SIZE,
    "query_repeats": QUERY_REPEATS,
    "k": K,
    "max_chunks": MAX_CHUNKS,
    "max_queries": MAX_QUERIES,
}

{'backends': ('chroma', 'pgvector'),
 'batch_size': 256,
 'query_repeats': 3,
 'k': 5,
 'max_chunks': None,
 'max_queries': None}

## Run Benchmark

This returns raw pandas DataFrames. It uses temporary benchmark collections and cleans them up after each run.

In [4]:
results = run_backend_benchmark(
    backends=BACKENDS,
    batch_size=BATCH_SIZE,
    query_repeats=QUERY_REPEATS,
    k=K,
    max_chunks=MAX_CHUNKS,
    max_queries=MAX_QUERIES,
    cleanup=True,
)

summaries = summarise_results(results)
results["parameters"]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6944.99it/s]

{'backends': ['chroma', 'pgvector'],
 'batch_size': 256,
 'query_repeats': 3,
 'k': 5,
 'max_chunks': None,
 'max_queries': None,
 'chunks_benchmarked': 5913,
 'reference_queries': 20,
 'collection_prefix': 'tpi_vectors_benchmark',
 'benchmark_id_prefix': 'tpi_vectors_benchmark__',
 'cleanup': True}

In [5]:
pd.DataFrame(results["errors"])

Empty DataFrame
Columns: []
Index: []

## Ingestion Speed

`total_embed_and_store_seconds` matches the professor's requested embed + store timing. `store_add_seconds` isolates just the backend write cost.

In [6]:
display(summaries.get("ingestion_summary", pd.DataFrame()))
display(results["ingestion_batches"])

,backend,chunks,batches,embed_seconds,store_add_seconds,total_embed_and_store_seconds,chunks_per_second_total,chunks_per_second_store_only
0,chroma,5913,24,32.678650,4.198599,36.877249,160.342763,1408.327005
1,pgvector,5913,24,28.219324,2.495041,30.714364,192.515786,2369.901175

,backend,batch_number,batch_size,store_add_seconds,store_chunks_per_second
0,chroma,1,256,0.180964,1414.648289
1,chroma,2,256,0.162379,1576.562992
2,chroma,3,256,0.161738,1582.804715
3,chroma,4,256,0.176848,1447.571818
4,chroma,5,256,0.178519,1434.017013
5,chroma,6,256,0.163281,1567.850491
6,chroma,7,256,0.162832,1572.171744
7,chroma,8,256,0.167365,1529.591388
8,chroma,9,256,0.160704,1592.994558
9,chroma,10,256,0.183529,1394.877774
10,chroma,11,256,0.176711,1448.692383
11,chroma,12,256,0.194173,1318.410234
12,chroma,13,256,0.167241,1530.728928
13,chroma,14,256,0.199504,1283.183096
14,chroma,15,256,0.171744,1490.589927
15,chroma,16,256,0.184401,1388.275673
16,chroma,17,256,0.159459,1605.429614
17,chroma,18,256,0.180231,1420.399054
18,chroma,19,256,0.267593,956.675404
19,chroma,20,256,0.221486,1155.830786
20,chroma,21,256,0.159846,1601.543568
21,chroma,22,256,0.176496,1450.457464
22,chroma,23,256,0.197930,1293.385734
23,chroma,24,25,0.043626,573.059334
24,pgvector,1,256,0.316840,807.979109
25,pgvector,2,256,0.106939,2393.894641
26,pgvector,3,256,0.106953,2393.565417
27,pgvector,4,256,0.100280,2552.841398
28,pgvector,5,256,0.096310,2658.085591
29,pgvector,6,256,0.106257,2409.257754
30,pgvector,7,256,0.095095,2692.056602
31,pgvector,8,256,0.095565,2678.810860
32,pgvector,9,256,0.114856,2228.885990
33,pgvector,10,256,0.093372,2741.707838
34,pgvector,11,256,0.096025,2665.973541
35,pgvector,12,256,0.092209,2776.292899
36,pgvector,13,256,0.089940,2846.336753
37,pgvector,14,256,0.090454,2830.159998
38,pgvector,15,256,0.091344,2802.588563
39,pgvector,16,256,0.096849,2643.279837
40,pgvector,17,256,0.092987,2753.082871
41,pgvector,18,256,0.090005,2844.294331
42,pgvector,19,256,0.089170,2870.930116
43,pgvector,20,256,0.095701,2675.011003
44,pgvector,21,256,0.092973,2753.478924
45,pgvector,22,256,0.139182,1839.323814
46,pgvector,23,256,0.095383,2683.908203
47,pgvector,24,25,0.010352,2414.943521

## Query Latency

The professor asked for three runs and median latency. The summary table includes median, mean, p95, min, and max.

In [7]:
display(summaries.get("query_latency_summary", pd.DataFrame()))
display(results["query_latency"].head(30))

,backend,filter_name,runs,median_seconds,mean_seconds,p95_seconds,min_seconds,max_seconds
0,chroma,company_filter,60,0.005224,0.005189,0.005835,0.004525,0.006585
4,pgvector,company_filter,60,0.004896,0.005089,0.007792,0.002896,0.009749
1,chroma,sector_filter,60,0.004196,0.004259,0.005370,0.002762,0.005826
5,pgvector,sector_filter,60,0.007087,0.007283,0.009807,0.005149,0.010756
2,chroma,unfiltered,60,0.000982,0.001066,0.001257,0.000843,0.004044
6,pgvector,unfiltered,60,0.013581,0.013837,0.016287,0.011821,0.018594
3,chroma,year_filter,60,0.005237,0.005304,0.006198,0.004453,0.006705
7,pgvector,year_filter,60,0.007166,0.007296,0.009917,0.004456,0.010586

,backend,filter_name,repeat,query,k,seconds,returned,top_chunk_id,top_score
0,chroma,unfiltered,1,What are AGL's emissions targets?,5,0.004044,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0020,0.732535
1,chroma,unfiltered,1,What power stations does AGL operate?,5,0.001070,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0065,0.586245
2,chroma,unfiltered,1,What is AGL's approach to renewable energy investment?,5,0.000990,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0067,0.776811
3,chroma,unfiltered,1,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,5,0.000944,5,tpi_vectors_benchmark__Alliant_3-Alliant-Energy-Sustainability-Performance-Data-v08-02-2018_elem_0037,0.693020
4,chroma,unfiltered,1,What are Alliant Energy's Clean Energy Vision goals?,5,0.000915,5,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0034,0.672022
5,chroma,unfiltered,1,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,5,0.001255,5,tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0088,0.599546
6,chroma,unfiltered,1,What are CenterPoint Energy's Scope 1 and Scope 2 greenhouse gas emissions goals?,5,0.001247,5,tpi_vectors_benchmark__Center_Point_Energy_Transition_Goals_-_CenterPoint_Energy_Sustainability_elem_0001,0.799538
7,chroma,unfiltered,1,What are Chubu Electric Power Group's 2050 zero-emissions goals and supporting decarbonization actions?,5,0.001020,5,tpi_vectors_benchmark__Chubu_Zero_Emissions_Challenge_(March_2021)_elem_0000,0.852365
8,chroma,unfiltered,1,"What are BHP's Scope 1, Scope 2, and Scope 3 emissions reduction targets for 2030?",5,0.001054,5,tpi_vectors_benchmark__BHP_200910_BHPClimateChangeReport_2020_elem_0034,0.762394
9,chroma,unfiltered,1,What are Freeport-McMoRan's four 2030 Scope 1 and Scope 2 GHG emissions reduction targets?,5,0.001137,5,tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126,0.658937
10,chroma,unfiltered,1,"What are Glencore's Scope 1, 2, and 3 emissions reduction targets?",5,0.001172,5,tpi_vectors_benchmark__Glencore_2022-Climate-Report_elem_0184,0.693548
11,chroma,unfiltered,1,How does Rio Tinto calculate Scope 3 emissions from processing copper concentrate?,5,0.001165,5,tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-123-report-addendum_elem_0070,0.724122
12,chroma,unfiltered,1,What iron ore portfolio risks and opportunities does Rio Tinto identify in the low-carbon transition?,5,0.001051,5,tpi_vectors_benchmark__Rio_Tinto_2024-annual-report_elem_0539,0.697171
13,chroma,unfiltered,1,"How does Rio Tinto define Scope 1, Scope 2, and Scope 3 emissions?",5,0.001011,5,tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-123-report-addendum_elem_0037,0.680682
14,chroma,unfiltered,1,"What are Vale's Scope 1, Scope 2, Scope 3, and renewable energy climate targets?",5,0.001160,5,tpi_vectors_benchmark__Vale_Integrated_Report_Vale_2024_elem_0242,0.645670
15,chroma,unfiltered,1,What are the FY 2025 targets for the Vedanta Zinc International (VZI) Renewable Energy Project at Gamsberg?,5,0.001303,5,tpi_vectors_benchmark__Vedanta_Sustainability-Report-FY2024_elem_0316,0.680496
16,chroma,unfiltered,1,"What are Danone's SBTi emissions reduction targets for Scope 1, Scope 2, and Scope 3?",5,0.001012,5,tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126,0.713785
17,chroma,unfiltered,1,What are Hershey's priority cocoa and environmental goals?,5,0.000858,5,tpi_vectors_benchmark__Hershey_Company_ESG_Report_2021_elem_0177,0.766942
18,chroma,unfiltered,1,"How did Orkla define short, medium, and long-term time horizons for climate risks and targets in 2024?",5,0.000885,5,tpi_vectors_benchmark__Orkla_CDP_2023_elem_0021,0.722778
19,chroma,unfiltered,1,What were Kraft Heinz's environmental sustainability goals in 2024?,5,0.001029,5,tpi_vectors_benchmark__Kraft_Heinz_ESG_Report_2024_elem_0136,0.751170
20,chroma,unfiltered,2,What are AGL's emissions targets?,5,0.001223,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0020,0.732535
21,chroma,unfiltered,2,What power stations does AGL operate?,5,0.000975,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0065,0.586245
22,chroma,unfiltered,2,What is AGL's approach to renewable energy investment?,5,0.000976,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0067,0.776811
23,chroma,unfiltered,2,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,5,0.000941,5,tpi_vectors_benchmark__Alliant_3-Alliant-Energy-Sustainability-Performance-Data-v08-02-2018_elem_0037,0.693020
24,chroma,unfiltered,2,What are Alliant Energy's Clean Energy Vision goals?,5,0.000897,5,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0034,0.672022
25,chroma,unfiltered,2,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,5,0.000945,5,tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0088,0.599546
26,chroma,unfiltered,2,What are CenterPoint Energy's Scope 1 and Scope 2 greenhouse gas emissions goals?,5,0.000978,5,tpi_vectors_benchmark__Center_Point_Energy_Transition_Goals_-_CenterPoint_Energy_Sustainability_elem_0001,0.799538
27,chroma,unfiltered,2,What are Chubu Electric Power Group's 2050 zero-emissions goals and supporting decarbonization actions?,5,0.000961,5,tpi_vectors_benchmark__Chubu_Zero_Emissions_Challenge_(March_2021)_elem_0000,0.852365
28,chroma,unfiltered,2,"What are BHP's Scope 1, Scope 2, and Scope 3 emissions reduction targets for 2030?",5,0.000979,5,tpi_vectors_benchmark__BHP_200910_BHPClimateChangeReport_2020_elem_0034,0.762394
29,chroma,unfiltered,2,What are Freeport-McMoRan's four 2030 Scope 1 and Scope 2 GHG emissions reduction targets?,5,0.001166,5,tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126,0.658937

## Recall@5, Precision@5, and MRR

In [8]:
display(summaries.get("retrieval_quality_summary", pd.DataFrame()))
display(results["retrieval_quality"])

    backend  mean_mrr  mean_recall@5  mean_precision@5
0    chroma    0.4125       0.426667              0.18
1  pgvector    0.4125       0.426667              0.18

,backend,query,recall@5,precision@5,mrr,relevant_available,relevant_returned
0,chroma,"How did Orkla define short, medium, and long-term time horizons for climate risks and targets in 2024?",0.000000,0.0,0.000000,1,0
1,chroma,How does Rio Tinto calculate Scope 3 emissions from processing copper concentrate?,0.000000,0.0,0.000000,2,0
2,chroma,"How does Rio Tinto define Scope 1, Scope 2, and Scope 3 emissions?",0.000000,0.0,0.000000,1,0
3,chroma,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,0.000000,0.0,0.000000,3,0
4,chroma,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,0.500000,0.2,0.333333,2,1
5,chroma,What are AGL's emissions targets?,0.250000,0.2,0.500000,4,1
6,chroma,What are Alliant Energy's Clean Energy Vision goals?,0.000000,0.0,0.000000,3,0
7,chroma,"What are BHP's Scope 1, Scope 2, and Scope 3 emissions reduction targets for 2030?",0.200000,0.2,0.333333,5,1
8,chroma,What are CenterPoint Energy's Scope 1 and Scope 2 greenhouse gas emissions goals?,0.666667,0.4,1.000000,3,2
9,chroma,What are Chubu Electric Power Group's 2050 zero-emissions goals and supporting decarbonization actions?,0.666667,0.4,1.000000,3,2
10,chroma,"What are Danone's SBTi emissions reduction targets for Scope 1, Scope 2, and Scope 3?",1.000000,0.2,0.500000,1,1
11,chroma,What are Freeport-McMoRan's four 2030 Scope 1 and Scope 2 GHG emissions reduction targets?,1.000000,0.2,0.333333,1,1
12,chroma,"What are Glencore's Scope 1, 2, and 3 emissions reduction targets?",0.000000,0.0,0.000000,1,0
13,chroma,What are Hershey's priority cocoa and environmental goals?,0.333333,0.2,0.500000,3,1
14,chroma,"What are Vale's Scope 1, Scope 2, Scope 3, and renewable energy climate targets?",0.250000,0.2,0.250000,4,1
15,chroma,What are the FY 2025 targets for the Vedanta Zinc International (VZI) Renewable Energy Project at Gamsberg?,0.666667,0.4,1.000000,3,2
16,chroma,What iron ore portfolio risks and opportunities does Rio Tinto identify in the low-carbon transition?,0.000000,0.0,0.000000,2,0
17,chroma,What is AGL's approach to renewable energy investment?,1.000000,0.4,1.000000,2,2
18,chroma,What power stations does AGL operate?,1.000000,0.4,0.500000,2,2
19,chroma,What were Kraft Heinz's environmental sustainability goals in 2024?,1.000000,0.2,1.000000,1,1
20,pgvector,"How did Orkla define short, medium, and long-term time horizons for climate risks and targets in 2024?",0.000000,0.0,0.000000,1,0
21,pgvector,How does Rio Tinto calculate Scope 3 emissions from processing copper concentrate?,0.000000,0.0,0.000000,2,0
22,pgvector,"How does Rio Tinto define Scope 1, Scope 2, and Scope 3 emissions?",0.000000,0.0,0.000000,1,0
23,pgvector,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,0.000000,0.0,0.000000,3,0
24,pgvector,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,0.500000,0.2,0.333333,2,1
25,pgvector,What are AGL's emissions targets?,0.250000,0.2,0.500000,4,1
26,pgvector,What are Alliant Energy's Clean Energy Vision goals?,0.000000,0.0,0.000000,3,0
27,pgvector,"What are BHP's Scope 1, Scope 2, and Scope 3 emissions reduction targets for 2030?",0.200000,0.2,0.333333,5,1
28,pgvector,What are CenterPoint Energy's Scope 1 and Scope 2 greenhouse gas emissions goals?,0.666667,0.4,1.000000,3,2
29,pgvector,What are Chubu Electric Power Group's 2050 zero-emissions goals and supporting decarbonization actions?,0.666667,0.4,1.000000,3,2
30,pgvector,"What are Danone's SBTi emissions reduction targets for Scope 1, Scope 2, and Scope 3?",1.000000,0.2,0.500000,1,1
31,pgvector,What are Freeport-McMoRan's four 2030 Scope 1 and Scope 2 GHG emissions reduction targets?,1.000000,0.2,0.333333,1,1
32,pgvector,"What are Glencore's Scope 1, 2, and 3 emissions reduction targets?",0.000000,0.0,0.000000,1,0
33,pgvector,What are Hershey's priority cocoa and environmental goals?,0.333333,0.2,0.500000,3,1
34,pgvector,"What are Vale's Scope 1, Scope 2, Scope 3, and renewable energy climate targets?",0.250000,0.2,0.250000,4,1
35,pgvector,What are the FY 2025 targets for the Vedanta Zinc International (VZI) Renewable Energy Project at Gamsberg?,0.666667,0.4,1.000000,3,2
36,pgvector,What iron ore portfolio risks and opportunities does Rio Tinto identify in the low-carbon transition?,0.000000,0.0,0.000000,2,0
37,pgvector,What is AGL's approach to renewable energy investment?,1.000000,0.4,1.000000,2,2
38,pgvector,What power stations does AGL operate?,1.000000,0.4,0.500000,2,2
39,pgvector,What were Kraft Heinz's environmental sustainability goals in 2024?,1.000000,0.2,1.000000,1,1

## Scores and Ranking Parity

This checks whether both backends return the same top-k chunk IDs in the same order.

In [9]:
display(summaries.get("score_summary", pd.DataFrame()))
display(summaries.get("ranking_parity_summary", pd.DataFrame()))
display(results["ranking_parity"])
display(results["topk_results"].head(30))

    backend  returned_scores  mean_score  median_score  min_score  max_score
0    chroma              100    0.674787      0.672781   0.537894   0.852365
1  pgvector              100    0.674787      0.672781   0.537894   0.852365

,baseline_backend,comparison_backend,queries_compared,same_order_queries,same_set_queries
0,chroma,pgvector,20,20,20

,baseline_backend,comparison_backend,query,same_order,same_set,baseline_ids,comparison_ids
0,chroma,pgvector,"How did Orkla define short, medium, and long-term time horizons for climate risks and targets in 2024?",True,True,"[tpi_vectors_benchmark__Orkla_CDP_2023_elem_0021, tpi_vectors_benchmark__Orkla_CDP_2023_elem_0081, tpi_vectors_benchmark__Orkla_CDP_2023...","[tpi_vectors_benchmark__Orkla_CDP_2023_elem_0021, tpi_vectors_benchmark__Orkla_CDP_2023_elem_0081, tpi_vectors_benchmark__Orkla_CDP_2023..."
1,chroma,pgvector,How does Rio Tinto calculate Scope 3 emissions from processing copper concentrate?,True,True,"[tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-123-report-addendum_elem_0070, tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-...","[tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-123-report-addendum_elem_0070, tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-..."
2,chroma,pgvector,"How does Rio Tinto define Scope 1, Scope 2, and Scope 3 emissions?",True,True,"[tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-123-report-addendum_elem_0037, tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-...","[tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-123-report-addendum_elem_0037, tpi_vectors_benchmark__Rio_Tinto_2024-climate-scope-..."
3,chroma,pgvector,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,True,True,"[tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0088, tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0034, tpi_vectors_benchmark__...","[tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0088, tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0034, tpi_vectors_benchmark__..."
4,chroma,pgvector,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,True,True,"[tpi_vectors_benchmark__Alliant_3-Alliant-Energy-Sustainability-Performance-Data-v08-02-2018_elem_0037, tpi_vectors_benchmark__Alliant_C...","[tpi_vectors_benchmark__Alliant_3-Alliant-Energy-Sustainability-Performance-Data-v08-02-2018_elem_0037, tpi_vectors_benchmark__Alliant_C..."
5,chroma,pgvector,What are AGL's emissions targets?,True,True,"[tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0020, tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0041, tpi_vec...","[tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0020, tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0041, tpi_vec..."
6,chroma,pgvector,What are Alliant Energy's Clean Energy Vision goals?,True,True,"[tpi_vectors_benchmark__Alliant_CDP_2022_elem_0034, tpi_vectors_benchmark__Alliant_CDP_2022_elem_0234, tpi_vectors_benchmark__Alliant_CD...","[tpi_vectors_benchmark__Alliant_CDP_2022_elem_0034, tpi_vectors_benchmark__Alliant_CDP_2022_elem_0234, tpi_vectors_benchmark__Alliant_CD..."
7,chroma,pgvector,"What are BHP's Scope 1, Scope 2, and Scope 3 emissions reduction targets for 2030?",True,True,"[tpi_vectors_benchmark__BHP_200910_BHPClimateChangeReport_2020_elem_0034, tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126,...","[tpi_vectors_benchmark__BHP_200910_BHPClimateChangeReport_2020_elem_0034, tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126,..."
8,chroma,pgvector,What are CenterPoint Energy's Scope 1 and Scope 2 greenhouse gas emissions goals?,True,True,"[tpi_vectors_benchmark__Center_Point_Energy_Transition_Goals_-_CenterPoint_Energy_Sustainability_elem_0001, tpi_vectors_benchmark__Cente...","[tpi_vectors_benchmark__Center_Point_Energy_Transition_Goals_-_CenterPoint_Energy_Sustainability_elem_0001, tpi_vectors_benchmark__Cente..."
9,chroma,pgvector,What are Chubu Electric Power Group's 2050 zero-emissions goals and supporting decarbonization actions?,True,True,"[tpi_vectors_benchmark__Chubu_Zero_Emissions_Challenge_(March_2021)_elem_0000, tpi_vectors_benchmark__Chubu_Zero_Emissions_Challenge_(Ma...","[tpi_vectors_benchmark__Chubu_Zero_Emissions_Challenge_(March_2021)_elem_0000, tpi_vectors_benchmark__Chubu_Zero_Emissions_Challenge_(Ma..."
10,chroma,pgvector,"What are Danone's SBTi emissions reduction targets for Scope 1, Scope 2, and Scope 3?",True,True,"[tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126, tpi_vectors_benchmark__Danone_2023_Danone_SBTi_Target_elem_0010, tpi_vec...","[tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126, tpi_vectors_benchmark__Danone_2023_Danone_SBTi_Target_elem_0010, tpi_vec..."
11,chroma,pgvector,What are Freeport-McMoRan's four 2030 Scope 1 and Scope 2 GHG emissions reduction targets?,True,True,"[tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126, tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0051, tpi_vecto...","[tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0126, tpi_vectors_benchmark__Freeport_2022_Climate-Report_elem_0051, tpi_vecto..."
12,chroma,pgvector,"What are Glencore's Scope 1, 2, and 3 emissions reduction targets?",True,True,"[tpi_vectors_benchmark__Glencore_2022-Climate-Report_elem_0184, tpi_vectors_benchmark__Glencore_2022-Climate-Report_elem_0042, tpi_vecto...","[tpi_vectors_benchmark__Glencore_2022-Climate-Report_elem_0184, tpi_vectors_benchmark__Glencore_2022-Climate-Report_elem_0042, tpi_vecto..."
13,chroma,pgvector,What are Hershey's priority cocoa and environmental goals?,True,True,"[tpi_vectors_benchmark__Hershey_Company_ESG_Report_2021_elem_0177, tpi_vectors_benchmark__Hershey_Company_ESG_Report_2021_elem_0028, tpi...","[tpi_vectors_benchmark__Hershey_Company_ESG_Report_2021_elem_0177, tpi_vectors_benchmark__Hershey_Company_ESG_Report_2021_elem_0028, tpi..."
14,chroma,pgvector,"What are Vale's Scope 1, Scope 2, Scope 3, and renewable energy climate targets?",True,True,"[tpi_vectors_benchmark__Vale_Integrated_Report_Vale_2024_elem_0242, tpi_vectors_benchmark__Vale_Integrated_Report_Vale_2024_elem_0388, t...","[tpi_vectors_benchmark__Vale_Integrated_Report_Vale_2024_elem_0242, tpi_vectors_benchmark__Vale_Integrated_Report_Vale_2024_elem_0388, t..."
15,chroma,pgvector,What are the FY 2025 targets for the Vedanta Zinc International (VZI) Renewable Energy Project at Gamsberg?,True,True,"[tpi_vectors_benchmark__Vedanta_Sustainability-Report-FY2024_elem_0316, tpi_vectors_benchmark__Vedanta_Sustainability-Report-FY2024_elem...","[tpi_vectors_benchmark__Vedanta_Sustainability-Report-FY2024_elem_0316, tpi_vectors_benchmark__Vedanta_Sustainability-Report-FY2024_elem..."
16,chroma,pgvector,What iron ore portfolio risks and opportunities does Rio Tinto identify in the low-carbon transition?,True,True,"[tpi_vectors_benchmark__Rio_Tinto_2024-annual-report_elem_0539, tpi_vectors_benchmark__Rio_Tinto_2024-annual-report_elem_0537, tpi_vecto...","[tpi_vectors_benchmark__Rio_Tinto_2024-annual-report_elem_0539, tpi_vectors_benchmark__Rio_Tinto_2024-annual-report_elem_0537, tpi_vecto..."
17,chroma,pgvector,What is AGL's approach to renewable energy investment?,True,True,"[tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0067, tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0022, tpi_vec...","[tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0067, tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0022, tpi_vec..."
18,chroma,pgvector,What power stations does AGL operate?,True,True,"[tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0065, tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0019, tpi_vec...","[tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0065, tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0019, tpi_vec..."
19,chroma,pgvector,What were Kraft Heinz's environmental sustainability goals in 2024?,True,True,"[tpi_vectors_benchmark__Kraft_Heinz_ESG_Report_2024_elem_0136, tpi_vectors_benchmark__Kraft_Heinz_ESG_Report_2024_elem_0159, tpi_vectors...","[tpi_vectors_benchmark__Kraft_Heinz_ESG_Report_2024_elem_0136, tpi_vectors_benchmark__Kraft_Heinz_ESG_Report_2024_elem_0159, tpi_vectors..."

,backend,query,rank,chunk_id,score,is_relevant,text_preview
0,chroma,What are AGL's emissions targets?,1,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0020,0.732535,False,RUNNING TITLE: affordable and sustainable energy options;\n\nHEADER (H2): 4\n\nMuch of the focus on AGL’s emissions is concentrated on t...
1,chroma,What are AGL's emissions targets?,2,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0041,0.713536,True,RUNNING TITLE: Source: Department of Environment (2014)\n\nHEADER (H2): 8\n\nTable 2 outlines the key parameters for establishing a Nati...
2,chroma,What are AGL's emissions targets?,3,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0050,0.713106,False,"RUNNING TITLE: Scenario 2 – '2 degree'\n\nHEADER (H2): 10\n\nemissions constraints, including: a carbon tax; emissions trading; regulati..."
3,chroma,What are AGL's emissions targets?,4,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0016,0.687635,False,RUNNING TITLE: CARBON CONSTRAINED FUTURE AGL’s approach to climate change mitigation: a scenario analysis\n\nHEADER (H2): INTRODUCTION\n...
4,chroma,What are AGL's emissions targets?,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0017,0.686768,False,RUNNING TITLE: affordable and sustainable energy options;\n\nHEADER (H2): 4\n\nMEASUREMENT OF GREENHOUSE GAS EMISSIONS AGL uses three ap...
5,chroma,What power stations does AGL operate?,1,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0065,0.586245,False,RUNNING TITLE: Figure 5: NPV Analysis of Emission Reduction Scenarios\n\nHEADER (H2): 12\n\nAs one of Australia’s largest electricity re...
6,chroma,What power stations does AGL operate?,2,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0019,0.583468,True,RUNNING TITLE: affordable and sustainable energy options;\n\nHEADER (H2): 4\n\nPREPARING FOR THE DECOMMISSIONING OF AGL’S EXISTING GENER...
7,chroma,What power stations does AGL operate?,3,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0058,0.582571,False,"RUNNING TITLE: Base NPV\n\nHEADER (H2): 11\n\nHowever, it is worth noting that for carbon pricing to be utilised effectively to drive em..."
8,chroma,What power stations does AGL operate?,4,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0006,0.553008,True,RUNNING TITLE: CARBON CONSTRAINED FUTURE AGL’s approach to climate change mitigation: a scenario analysis\n\nHEADER (H2): INTRODUCTION\n...
9,chroma,What power stations does AGL operate?,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0028,0.537894,False,"RUNNING TITLE: Bayswater\n\nHEADER (H2): 6\n\nSunverge: In February 2016, AGL invested $20 million in Sunverge which is a US-based energ..."
10,chroma,What is AGL's approach to renewable energy investment?,1,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0067,0.776811,True,RUNNING TITLE: Figure 5: NPV Analysis of Emission Reduction Scenarios\n\nHEADER (H2): 12\n\nAGL is positioning its business to capture v...
11,chroma,What is AGL's approach to renewable energy investment?,2,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0022,0.760339,False,RUNNING TITLE: affordable and sustainable energy options;\n\nHEADER (H2): 4\n\nOne of the critical activities that AGL is now undertakin...
12,chroma,What is AGL's approach to renewable energy investment?,3,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0024,0.740900,True,RUNNING TITLE: affordable and sustainable energy options;\n\nHEADER (H2): 4\n\nIt is in this context that AGL has developed an innovativ...
13,chroma,What is AGL's approach to renewable energy investment?,4,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0025,0.726715,False,RUNNING TITLE: affordable and sustainable energy options;\n\nHEADER (H2): 4\n\nThe opportunity for investors with long term investment m...
14,chroma,What is AGL's approach to renewable energy investment?,5,tpi_vectors_benchmark__AGL_Carbon_Constrained_Future_elem_0028,0.723348,False,"RUNNING TITLE: Bayswater\n\nHEADER (H2): 6\n\nSunverge: In February 2016, AGL invested $20 million in Sunverge which is a US-based energ..."
15,chroma,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,1,tpi_vectors_benchmark__Alliant_3-Alliant-Energy-Sustainability-Performance-Data-v08-02-2018_elem_0037,0.693020,False,"RUNNING TITLE: C O N T E N T S\n\nHEADER (H2): (no header)\n\nIn 2017, Alliant Energy invested $3.7 million in various research and deve..."
16,chroma,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,2,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0219,0.690142,False,"RUNNING TITLE: reliability requirements, evolution of new energy technologies, and customer adoption\n\nHEADER (H2): 15529873\n\nResearc..."
17,chroma,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,3,tpi_vectors_benchmark__Alliant_3-Alliant-Energy-Sustainability-Performance-Data-v08-02-2018_elem_0024,0.646379,True,"RUNNING TITLE: C O N T E N T S\n\nHEADER (H2): (no header)\n\n For our growing wind turbine fleet, we have also supported EPRI-sponsore..."
18,chroma,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,4,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0118,0.621246,False,"RUNNING TITLE: In 2021, Alliant Energy received approval from the Wisconsin Public Service Commis‐\n\nHEADER (H2): tives will benefit ou..."
19,chroma,How much electricity and natural gas did Alliant Energy's energy efficiency programs save in 2017?,5,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0132,0.615562,False,"RUNNING TITLE: In 2021, Alliant Energy received approval from the Wisconsin Public Service Commis‐\n\nHEADER (H2): tives will benefit ou..."
20,chroma,What are Alliant Energy's Clean Energy Vision goals?,1,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0034,0.672022,False,"HEADER (H2): pressed in, or implied by, the statements. Actual results could be materially affected by\n\nAlliant Energy is focused on e..."
21,chroma,What are Alliant Energy's Clean Energy Vision goals?,2,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0234,0.664342,False,RUNNING TITLE: Our Clean Energy Vision goals\n\nHEADER (H2): Protection Agency (EPA) mandatory Greenhouse Gas Reporting Program regulati...
22,chroma,What are Alliant Energy's Clean Energy Vision goals?,3,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0249,0.653881,False,RUNNING TITLE: Our Clean Energy Vision goals\n\nHEADER (H2): Protection Agency (EPA) mandatory Greenhouse Gas Reporting Program regulati...
23,chroma,What are Alliant Energy's Clean Energy Vision goals?,4,tpi_vectors_benchmark__Alliant_3-Alliant-Energy-Sustainability-Performance-Data-v08-02-2018_elem_0037,0.603397,False,"RUNNING TITLE: C O N T E N T S\n\nHEADER (H2): (no header)\n\nIn 2017, Alliant Energy invested $3.7 million in various research and deve..."
24,chroma,What are Alliant Energy's Clean Energy Vision goals?,5,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0223,0.600695,False,"RUNNING TITLE: reliability requirements, evolution of new energy technologies, and customer adoption\n\nHEADER (H2): 15529873\n\nAlliant..."
25,chroma,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,1,tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0088,0.599546,False,"RUNNING TITLE: Increases in fuel or fuel- handling\n\nHEADER (H2): Magnitude of impact\n\nsources such as coal, natural gas, wind,\nsun,..."
26,chroma,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,2,tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0034,0.591262,False,RUNNING TITLE: moratorium on new renewables development; restrictions on\n\nHEADER (H2): Position\n\nchanges to siting requirements that...
27,chroma,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,3,tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0027,0.579680,False,RUNNING TITLE: experience with solar technology;\n\nHEADER (H2): improvements.\n\nAllocation that is designed to protect trade-exposed i...
28,chroma,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,4,tpi_vectors_benchmark__Alliant_CDP_2022_elem_0050,0.578990,False,RUNNING TITLE: Monetary reward\n\nHEADER (H2): capital investments expanding company-owned renewable generation as well as invest‐\n\nwo...
29,chroma,How has Capital Power's transition toward a lower-emitting and renewable energy portfolio contributed to its strategic advantage?,5,tpi_vectors_benchmark__Capital_Power_CDP2017_elem_0070,0.578153,False,RUNNING TITLE: 11-15 years\n\nHEADER (H2): Comment\n\nNorth America. All potential projects are evaluated using an internal price on car...

## Metadata Filters

The professor asks for company, year, and sector filtering. This table shows which `where` filters are available from the current chunk metadata.

In [10]:
display(results["metadata_filters"])
display(results["query_latency"].groupby(["backend", "filter_name"], as_index=False)["seconds"].median())

      filter_name                           where  available
0      unfiltered                            None       True
1  company_filter              {'company': 'AGL'}       True
2     year_filter                {'year': '2016'}       True
3   sector_filter  {'sector': 'Energy Utilities'}       True

    backend     filter_name   seconds
0    chroma  company_filter  0.005224
1    chroma   sector_filter  0.004196
2    chroma      unfiltered  0.000982
3    chroma     year_filter  0.005237
4  pgvector  company_filter  0.004896
5  pgvector   sector_filter  0.007087
6  pgvector      unfiltered  0.013581
7  pgvector     year_filter  0.007166

## Deployment Complexity

Concrete counts for setup complexity: extra services, Docker Compose line count, and clean-machine backend setup steps.

In [11]:
display(summaries.get("deployment_complexity_summary", pd.DataFrame()))

,backend,extra_services_required,docker_compose_total_lines,docker_compose_noncomment_lines,clean_machine_backend_steps,setup_notes
0,chroma,0,0,0,2,Install Python env; set VECTOR_STORE=chroma.
1,pgvector,1,26,23,5,Install Docker; set Postgres env vars; docker compose up; run Alembic; run pgvector smoke test.

## Code Legibility

Concrete counts for each backend implementation. If `radon` is installed in the kernel, this also includes cognitive-complexity scores.

In [12]:
display(summaries.get("code_legibility_summary", pd.DataFrame()))

,backend,path,line_count,import_count,radon_functions_classes,radon_max_complexity,radon_mean_complexity,radon_note
0,chroma,vector_store/chroma.py,110,5,7,4,2.142857,
1,pgvector,vector_store/pgvector.py,174,11,10,6,2.500000,

## Optional Save

Only run this after the tables look right.

In [13]:
# write_results_json(results, "evaluation_results.json")